# ===============================
# DATABASE CONFIGURATION - DEV
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/readhub_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:zendrix77777}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# SECRETS - DEV
# ===============================
app.jwt.secret=${APP_JWT_SECRET:ThisIsANewVeryLongAndVerySecureSecretKeyForReadHubHS512abcdef123}
app.jwtSecret=${APP_JWT_SECRET:ThisIsANewVeryLongAndVerySecureSecretKeyForReadHubHS512abcdef123}

spring.mail.username=${SPRING_MAIL_USERNAME:rivazendrix@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:ddzjgyygujpkjumg}
